### PR TITLE
Add debiasing testing 

### PR DESCRIPTION
**Pull request by vinferrer**
Closes # .

Changes proposed in this pull request:

- Adds testing to the debiasing functions
-

### CODE REVIEW

**Comment by vinferrer** [comment]
@eurunuela could you point me the parts of code that we don't need on `debasing_functions.py`?

**Comment by vinferrer** [comment]
@eurunuela Could you review if there is any part of the debiasing code that we don't use?

**Comment by eurunuela** [comment]
> @eurunuela Could you review if there is any part of the debiasing code that we don't use?

I think we use everything you haven't removed.

**Comment by vinferrer** [comment]
Then this is ready for review

**Review by eurunuela — APPROVED** [review]
LGTM!

**Pull request merged**
